const express = require("express")
const router = express.Router()
const { CreateBooking,UserBooking,DeleteBooking,UpdateStatus,GetAllBookings,get_all_service_providers_booking,get_all_service_providers_booking_completed,sendOTP,verifyOTP} = require("../controllers/Booking.controllers") 
router.route("/makeBooking").post(CreateBooking)
router.route("/UserBookings").post(UserBooking) 
router.route("/SPBookings").post(get_all_service_providers_booking) 
router.route("/SP_completed_Bookings").post(get_all_service_providers_booking_completed) 
router.route("/DeleteBookings").post(DeleteBooking)
router.route("/ChangeStatus").post(UpdateStatus) 
router.route("/all_Booking").get(GetAllBookings)
router.route("/sendOTP").post(sendOTP)
router.route("/verifyOTP").post(verifyOTP)
module.exports = router 